### PR TITLE
Fix for hang in Show function on Windows

### PR DESCRIPTION
**Pull request by dave3d**
It was re-deleting a previously deleted process.

### CODE REVIEW

**Comment by blowekamp** [comment]
This is great you tracked it down!

So the Delete method would get called twice?

Was there were we talked about the [resource acquisition is initialization](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization) (RAII) pattern? Here is a small example:
https://github.com/SimpleITK/SimpleITK/blob/master/Wrapping/Python/sitkPyCommand.cxx#L31-L46

**Comment by dave3d** [comment]
> This is great you tracked it down!
> 
> So the Delete method would get called twice?
> 
> Was there were we talked about the [resource acquisition is initialization](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization) (RAII) pattern? Here is a small example:
> https://github.com/SimpleITK/SimpleITK/blob/master/Wrapping/Python/sitkPyCommand.cxx#L31-L46

Did we talk about that?  I don't recall, but I am getting old.

Interestingly, the bug didn't seem to affect OS X or Linux, even though it happened for those Ones too.

**Comment by blowekamp** [comment]
The CI seemed to work well. Is this patch based on the release branch?

**Comment by dave3d** [comment]
It's off master.  Should I have done release?

**Comment by blowekamp** [comment]
Please rebase it onto release so that it can more easily be used to patch the release branch.

**Pull request merged**
