### PR TITLE
Add in place filter execution from r value references

### PR DESCRIPTION
**Pull request by blowekamp**
Running ITK filters in-place reduces memory usage and can improve performance (upto 6X). This PR utilizes C++ rvalue reference to automatically run the ITK Filters in place. Additionally, new image operation were overloaded with rvalue reference for the first parameter. This enable automatic enabling of ITK filter to run inplace when there are temporary image in an expression. Consider chaining of filters and operators with automatic improved efficiency.

### CODE REVIEW

**Comment by blowekamp** [comment]
C++ gurus: @hjmjohnson @N-Dekker 

Three location of interest:
- Rvalue execute implementation: https://github.com/SimpleITK/SimpleITK/pull/1021/files#diff-64a4760b11e86a896a997369092266acR117
- scope exit: https://github.com/SimpleITK/SimpleITK/pull/1021/files#diff-461c00b91f4e10365a05359f6b49b739R232
- Image operators: https://github.com/SimpleITK/SimpleITK/pull/1021/files#diff-1afb92d00f7d672268b15ca3cce49637R44

**Review by zivy — APPROVED** [review]
So many operators...

**Review by dave3d — APPROVED** [review]
Holy Guacamole!

**Comment by blowekamp** [comment]
@dave3d  Did you get a change to check out the patch again?

**Comment by dave3d** [comment]
Yeah, I did.  The latest patch worked.

**Pull request merged**
