### PR TITLE
Update elastix to July 10, 2024 hash

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by N-Dekker** [comment]
> A lot of "unused typedefs", "overloaded virtual", "unused parameter" etc. Is this expected or does something need to be corrected with the build?

Thanks for reporting, but I don't know! Maybe you use a different compiler version, or a different warning level. Can you give me the list of warnings with details? Are they at https://open.cdash.org/index.php?project=SimpleITK  ?

**Comment by blowekamp** [comment]
I saw those locally with Apple clang 14.0.0. I don't believe the extra warning flag enable for SimpelITK are passed to the Elastix build.

This CI for this failed with a missing header:
I saw those local. But the CI for this PR failed with a missing header:
https://open.cdash.org/viewBuildError.php?buildid=9567908

"[Elastix-prefix/include/Core/ComponentBaseClasses/elxFixedImagePyramidBase.h:26](http://github.com/SimpleITK/SimpleITK//blob/0dfd18c40d96ff4810b7d8dad1f68d21fe8a40d1/Elastix-prefix/include/Core/ComponentBaseClasses/elxFixedImagePyramidBase.h#L26):10: fatal error: itkMultiResolutionPyramidImageFilter.h: No such file or directory"

**Comment by N-Dekker** [comment]
> The CI for this PR failed with a missing header: I saw those local. But the CI for this PR failed with a missing header: https://open.cdash.org/viewBuildError.php?buildid=9567908
> 
> "[Elastix-prefix/include/Core/ComponentBaseClasses/elxFixedImagePyramidBase.h:26](https://github.com/SimpleITK/SimpleITK//blob/0dfd18c40d96ff4810b7d8dad1f68d21fe8a40d1/Elastix-prefix/include/Core/ComponentBaseClasses/elxFixedImagePyramidBase.h#L26):10: fatal error: itkMultiResolutionPyramidImageFilter.h: No such file or directory"

itkMultiResolutionPyramidImageFilter.h is here: https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Registration/Common/include/itkMultiResolutionPyramidImageFilter.h 

So I think the compiler command-line for "Code/ElastixTransformixWrappers/src/sitkElastixImageFilterImpl.cxx" at https://open.cdash.org/viewBuildError.php?buildid=9567908 should have something like:

     -I/.../SimpleITK-build/ITK/Modules/Registration/Common/include

But I don't see it 🤷 Is it missing somehow?

**Comment by blowekamp** [comment]
@N-Dekker I think the Elastix libraries did not express their build dependencies in a conventional way to they were explicitly add here: https://github.com/SimpleITK/SimpleITK/blob/master/Code/ElastixTransformixWrappers/src/CMakeLists.txt#L8 I am testing adding ITKRegistrationCommon now.

**Comment by N-Dekker** [comment]
@blowekamp I just tried to upgrade the elastix CI from macos-12 to macos-14: https://github.com/SuperElastix/elastix/tree/GitHubActions-macos-14

Unfortunately, it did _not_ give me the warnings you mentioned at https://github.com/SimpleITK/SimpleITK/pull/2104#issuecomment-2075030813  Instead, I just got:

> ld: warning: ignoring duplicate libraries: '-lm', '/.../ITK-build/lib/libITKCommon-5.4.a', ...

at https://my.cdash.org/viewBuildError.php?type=1&buildid=2549153

Do you have a suggestion how I can get "your" elastix warnings, instead?

**Comment by blowekamp** [comment]
There are some now showing in the CI dashboard for this PR here: https://open.cdash.org/viewBuildError.php?type=1&buildid=9570768

**Comment by N-Dekker** [comment]
@blowekamp I'm sorry to say the extra compiler flags (-Wunused-parameter -Wshadow -Wdeprecated-declarations -Woverloaded-virtual) produce more warnings than I expected. For -Wshadow alone, it's already 1000+: https://my.cdash.org/viewBuildError.php?type=1&buildid=2550567  So it takes me more time than expected 🤷  To be continued...

**Comment by blowekamp** [comment]
> @blowekamp I'm sorry to say the extra compiler flags (-Wunused-parameter -Wshadow -Wdeprecated-declarations -Woverloaded-virtual) produce more warnings than I expected. For -Wshadow alone, it's already 1000+: https://my.cdash.org/viewBuildError.php?type=1&buildid=2550567 So it takes me more time than expected 🤷 To be continued...

Thank you for working on this. Hopefully, you can find some tools to automate some of the cleanup.

**Comment by N-Dekker** [comment]
@blowekamp It took a while, but I think I addressed all of those (2000+) warnings, with elastix pull request https://github.com/SuperElastix/elastix/pull/1136 commit https://github.com/SuperElastix/elastix/commit/78fe482aaabac5cb42b19c9365718b80eea1833e, now at the main branch of  https://github.com/SuperElastix/elastix Thanks for your patience  😃  Can you please give it another try?

**Comment by blowekamp** [comment]
@N-Dekker Thanks again for addressing the compiler warning. Unfortunately Elastics seems to still be failing catastrophically with in SimpleITK: 
https://open.cdash.org/viewTest.php?onlyfailed&buildid=9715640


There previous working tag SuperElastix/elastix@3b27d0 was from May 2022. I am hoping that since you are more familiar with the elastic code you may easily know what need to be changed to get SimpleITK working again with elastic. 

Thanks you!

**Comment by N-Dekker** [comment]
@blowekamp Can you possibly give it another try, using the latest revision from the SuperElastix/elastix main branch? I'm not sure, but it _might_ help that we have recently removed the elastix OpenMP dependency:
- Merged pull request https://github.com/SuperElastix/elastix/pull/1188 commit https://github.com/SuperElastix/elastix/commit/e49c47fbb8bca796288796f85020c02ffe85b5d7

**Comment by N-Dekker** [comment]
@blowekamp Thanks Bradley. I see, macos and windows build fine now, but those self-hosted Ninja builds still fail. Is that still a show-stopper?

**Comment by blowekamp** [comment]
@N-Dekker Elastix is only enable on those two systems. All of the elastix tests are failing:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=9750008

Yes, it it a show stopper.

**Comment by N-Dekker** [comment]
> All of the elastix tests are failing: https://open.cdash.org/viewTest.php?onlyfailed&buildid=9750008

@blowekamp One of the errors I see there is from `ElastixImageFilter.InitialTransform`, saying:


```
Expected: resultImage1 = silx1.Execute() doesn't throw an exception.
  Actual: it throws itk::simple::GenericException with description "/var/lib/actions-runner/_work/SimpleITK/SimpleITK/Code/Common/src/sitkPimpleImageBase.hxx:969:
sitk::ERROR: The image pixel container is shared by other resources and presents aliasing issue.".
```

Apparently in `PimpleImage::InternalCheckBuffer(const itk::Image<TPixelType, NDimension> * image)`:

https://github.com/SimpleITK/SimpleITK/blob/5f4a2481381ac98313bd442b5119bb8477b2a160/Code/Common/src/sitkPimpleImageBase.hxx#L964-L969

Do you have a clue what that means?

**Comment by blowekamp** [comment]
> > All of the elastix tests are failing: https://open.cdash.org/viewTest.php?onlyfailed&buildid=9750008
> 
> @blowekamp One of the errors I see there is from `ElastixImageFilter.InitialTransform`, saying:
> 
> ```
> Expected: resultImage1 = silx1.Execute() doesn't throw an exception.
>   Actual: it throws itk::simple::GenericException with description "/var/lib/actions-runner/_work/SimpleITK/SimpleITK/Code/Common/src/sitkPimpleImageBase.hxx:969:
> sitk::ERROR: The image pixel container is shared by other resources and presents aliasing issue.".
> ```
> 
> Apparently in `PimpleImage::InternalCheckBuffer(const itk::Image<TPixelType, NDimension> * image)`:
> 
> https://github.com/SimpleITK/SimpleITK/blob/5f4a2481381ac98313bd442b5119bb8477b2a160/Code/Common/src/sitkPimpleImageBase.hxx#L964-L969
> 
> Do you have a clue what that means?

It mean there is another object or smart pointer holding a reference to the ITK's image buffer. This means it is not safe for SimpleITK to take ownership of the Image.

Just guessing that it is coming from here:
https://github.com/SimpleITK/SimpleITK/blob/5f4a2481381ac98313bd442b5119bb8477b2a160/Code/ElastixTransformixWrappers/src/sitkElastixImageFilter.cxx#L776

Looks like the itk::Image returned is converted to an sitk::Image before the ElastixImageFilter is destroyed. Likely something changed in the Elastix filter to hole onto the Image's Buffer after execution. I think looking at the reference count in at the end of the ElastixImageFilter::Execute method is something that can be tested in Elastix without building SimpleITK.

**Comment by blowekamp** [comment]
@N-Dekker  I made a change to the way the images are obtained from the elastix filter so the extra references are released before importing into SimpleITK Images.

**Review by zivy — APPROVED** [review]

**Comment by blowekamp** [comment]
@N-Dekker Thanks for working on addressing all the warnings. There are still some related to unused typedefs/using statements. I am going to merge the PR as it version of Elastix appears to work with these changes. Please feel free to recommend ( via PR )a tag or other hash.

**Pull request merged**
