### PR TITLE
Wrap Image's GetBuffer methods for Java

### PR DESCRIPTION
**Pull request by blowekamp**
Helps with #1215.

### CODE REVIEW

**Comment by blowekamp** [comment]
@haesleinhuepf This PR should expose the GetBuffer methods in Java. Hopefully, this provides a starting interface to transfer the image buffer in JAVA. 

From here a SimpleITK example can be developed to demonstrate how to transfer similar to the CSharpIntegration example. Would you care to contribute that?

**Comment by haesleinhuepf** [comment]
> Would you care to contribute that?

Sure! I would like to put it next to the Gaussian Example, which already exists on the website:
https://simpleitk.readthedocs.io/en/master/setUp.html#gaussianexample

I would love to take a closer look at it first, because I don't know yet how to build a Java example with CMake. However, I can't find the source for this example - do you know where it is comes from?

**Comment by blowekamp** [comment]
The code for that documentation page is under the docs directory [here](https://github.com/SimpleITK/SimpleITK/blob/master/docs/source/setUp.rst). Unfortunately, it looks like the code was manually copied instead of referencing the [example](https://github.com/SimpleITK/SimpleITK/blob/master/Examples/SimpleGaussian/SimpleGaussian.java) in the [examples directory](https://github.com/SimpleITK/SimpleITK/tree/master/Examples).

I'd like to see a new subdirectory in "Examples" for this example. The CMake infrastructure can be copied from similar examples, and I'll fix it up to get it working.

I'm going to try to get this patched merged today, so that this change will be build tonight and uploaded to the "latest" release in [Github releases](https://github.com/SimpleITK/SimpleITK/releases). That way you will not have have to build SimpleITK yourself.

**Review by zivy — APPROVED** [review]
LGTM

**Comment by haesleinhuepf** [comment]
> That way you will not have have to build SimpleITK yourself.

You are awesome! Thanks! I will come back with the example as a PR :-)

**Comment by haesleinhuepf** [comment]
Hey @blowekamp ,

just a quick question: The getBufferAsFloat method now returns an object of that kind:
```
public class SWIGTYPE_p_float {
    private transient long swigCPtr;

    protected SWIGTYPE_p_float(long var1, boolean var3) {
        this.swigCPtr = var1;
    }

    protected SWIGTYPE_p_float() {
        this.swigCPtr = 0L;
    }

    protected static long getCPtr(SWIGTYPE_p_float var0) {
        return var0 == null ? 0L : var0.swigCPtr;
    }
}
```

It's not so trivial to retrieve the actual pointer to the data from that as everything is private/protected. Furthermore, I was hoping to get a Java Native-Input-Output Buffer, e.g. a [FloatBuffer](https://docs.oracle.com/javase/7/docs/api/java/nio/FloatBuffer.html). I think I can translate your SWIGTYPE_p_float  in such a buffer but I will take quite some effort. Thus, before I start investigating: Is there anything on SimpleITK side that could facilitate this conversion?

Thanks again!

**Comment by blowekamp** [comment]
Looks like the current SWIG type map is not as useful as I hoped.

**Comment by haesleinhuepf** [comment]
I think, I could also allocate memory (a native buffer kind) of the right size and hand over a pointer to SimpleITK, if that's easier...

**Comment by haesleinhuepf** [comment]
@blowekamp 

I managed it! 

Just one little request stays: If you could make the getCPtr() methods in the SWIGTYPE classes public that would be great. 
```
public static long getCPtr(SWIGTYPE_p_float var0) {...
```

I could then spare [this part](https://github.com/clij/clijx-assistant-simpleitk/blob/2a54f87654fb3f7985f97f92f525b898f13e297e/src/main/java/net/haesleinhuepf/clijx/simpleitk/CLIJSimpleITKUtilities.java#L18-L34).

I'll boil it down to a simpler Java example and send it as PR to SimpleITK then. 

You wouldn't believe how happy I am to eventually see SimpleITK in ImageJ ;-)

zero_crossing_edge_detection

Thanks again!

**Comment by haesleinhuepf** [comment]
Hm, if you return a ByteBuffer always, users may get issues with big/little endian. Also not sure if a ByteBuffer can be casted to a FloatBuffer...

**Comment by blowekamp** [comment]
> Hm, if you return a ByteBuffer always, users may get issues with big/little endian. Also not sure if a ByteBuffer can be casted to a FloatBuffer...

Yes, there are many details to work out. The `ByteBuffer` has the [`asFloatBuffer`](https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html#asFloatBuffer()) method and many other methods as*Buffer. Please give it a closer look and let me know if it would work.

**Comment by haesleinhuepf** [comment]
> Please give it a closer look and let me know if it would work.

The `ByteBuffer.asFloatBuffer()` appears not returning a "normal" `FloatBuffer`.

My test code:
```
public static void main(String[] args) {
        // create temporary memory on the GPU
        CLIJ2 clij2 = CLIJ2.getInstance();
        ClearCLBuffer temp = clij2.create(new long[]{8,1}, NativeTypeEnum.Float);

        float[] array = new float[]{1, 2, 3, 4.5f, 5, 6.5f, 7, 8};
        FloatBuffer f = FloatBuffer.wrap(array);
        ByteBuffer b = ByteBuffer.allocate(8 * 4);

        // copy from float array to float image
        temp.readFrom(f, true);
        temp.writeTo(b, true);

        // test conversion
        FloatBuffer c = b.asFloatBuffer(); 

        // empty float array
        for (int i = 0; i < array.length; i ++) {
            array[i] = 0;
        }

        // copy back
        temp.readFrom(c, true); // -- crashes here
        temp.writeTo(f, true);

        System.out.println(Arrays.toString(array));

    }
```

Returns this error:
```
Exception in thread "main" net.haesleinhuepf.clij.clearcl.exceptions.ClearCLException: The buffer must have an array or be direct
	at net.haesleinhuepf.clij.clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:163)
	at net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL.wrap(ClearCLBackendJOCL.java:1123)
	at net.haesleinhuepf.clij.clearcl.ClearCLBuffer.readFrom(ClearCLBuffer.java:509)
	at net.haesleinhuepf.clij.clearcl.ClearCLBuffer.readFrom(ClearCLBuffer.java:477)
	at net.haesleinhuepf.clijx.simpleitk.CLIJSimpleITKUtilities.main(CLIJSimpleITKUtilities.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.IllegalArgumentException: The buffer must have an array or be direct
	at org.jocl.Pointer.to(Pointer.java:226)
	at net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL.lambda$wrap$37(ClearCLBackendJOCL.java:1124)
	at net.haesleinhuepf.clij.clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:156)
	... 9 more
```

So, it may work in general, but not in our case. Not sure if fixing this issue in [jocl](https://github.com/gpu/JOCL/blob/master/src/main/java/org/jocl/Pointer.java#L226) makes sense. Furthermore, if we copy this float buffer to avoid the error, we would have two copy operations, which I'd like to avoid for performance reasons. Getting a pointer from SimpleITK which I can copy to GPU memory is kind of the ideal scenario...

**Pull request merged**
