### PR TITLE
fix for unused variable warning

### PR DESCRIPTION
**Pull request by dave3d**

### CODE REVIEW

**Review by zivy — COMMENTED** [review]
Several requests after looking at the code and read-the-docs:

1. Add the C# example to the RTD pages (currently only Python and R tabs are visible).
2. Modify all examples so that they write the full res image, `corrected_image_full_resolution`, using the argv[2] parameter instead of the resized image which is done in the current code.
3. If the program received a shrink factor, argv[3], write the shrunk image, `corrected_image`, to disk too using a constant name.

This would address the warning and the code would make more logical sense.

**Comment by dave3d** [comment]
> Several requests after looking at the code and read-the-docs:
> 
> 1. Add the C# example to the RTD pages (currently only Python and R tabs are visible).
> 2. Modify all examples so that they write the full res image, `corrected_image_full_resolution`, using the argv[2] parameter instead of the resized image which is done in the current code.
> 3. If the program received a shrink factor, argv[3], write the shrunk image, `corrected_image`, to disk too using a constant name.
> 
> This would address the C# warning and the code would make more logical sense.

That makes sense.  I'll make the changes.

I didn't know the code, so I wasn't sure why the resized image was written by default.

**Review by zivy — APPROVED** [review]
Minor observation, possibly use underscore in the "shrunk" file names instead of dot? The dot separator seems strange and I don't know what windows does with it in terms of display of file extension, maybe it does the right thing.

**Comment by dave3d** [comment]
> Minor observation, possibly use underscore in the "shrunk" file names instead of dot? The dot separator seems strange and I don't know what windows does with it in terms of display of file extension, maybe it does the right thing.

Looking at the other testing output files on Windows, they tend to use dash, '-'.  So I'll go with that.  I don't think Windows really cares, though, since some do have  dots, and the look ok in Windows.

**Pull request merged**
