### PR TITLE
ENH: Remove the hacks to do with enumerations and swig/R

### PR DESCRIPTION
**Pull request by richardbeare**
Changes by Richard Beare, for which there are PR for swig 4.0,
make these hacks redundant. The relevant changes for swig 4.0
modify the R enumeration behaviour so that calls to the
C layer are used to determine the underlying enumeration
values.

Testing of R:

### CODE REVIEW

**Comment by blowekamp** [comment]
This PR is block by an update to SWIG 4.0?

**Comment by blowekamp** [comment]
> This PR is block by an update to SWIG 4.0?

@richardbeare Is this code dependent upon updating to SWIG 4?

**Comment by richardbeare** [comment]
Yes, it is dependent on Swig 4.0

**Comment by blowekamp** [comment]
@richardbeare We have just updated to SWIG 4.0, can you please rebase this PR?

**Comment by richardbeare** [comment]
@blowekamp It has been too long. Do I rebase to master or release?

**Comment by dave3d** [comment]
Master, right?

**Comment by blowekamp** [comment]
master, we just updated to SWIG 4.0 on master.

**Comment by richardbeare** [comment]
Rebased and created new PR #1055.

**Comment by blowekamp** [comment]
Contribution merged in  #1055.

**Pull request closed without merging**
