### PR TITLE
Merge Lint and Spell workflows

### PR DESCRIPTION
**Pull request by dave3d**
python-lint.yml and python-spell.yml have been combined into one
new workflow, PythonLintAndSpell.yml.

### CODE REVIEW

**Review by blowekamp — COMMENTED** [review]
L1: Update the name of this work flow
L10: The name of the job is "build", please update too

**Comment by dave3d** [comment]
> L1: Update the name of this work flow
> L10: The name of the job is "build", please update too

Oops.  Should I have two separate jobs, lint and spell?

**Comment by blowekamp** [comment]
> > L1: Update the name of this work flow
> > L10: The name of the job is "build", please update too
> 
> Oops. Should I have two separate jobs, lint and spell?

It will take a little more time to install the dependencies, but I think the workflow into tow jobs makes sense and should allow developers to more quickly determine the source of a CI failure.

**Review by zivy — COMMENTED** [review]
Not too sure about these changes. Previously linting and spell checking were separate workflows which ran independently. With this change they are two jobs in a single workflow. Not sure if this change makes sense, unless the intent is to make spell checking run only if linting succeeds (add a `needs: lint` to the spell job).

**Comment by dave3d** [comment]
They really are separate things, but Brad asked that I combine them.  Note that the linting is checking the formatting of the Python code, while the spell checking is done on comments the C++ header files.  It just happens that the spell checking is written in Python.

**Comment by blowekamp** [comment]
@zivy With the addition of Doxygen and the Build workflows, there are starting to be to many workflows in the GHA GUI. We can kinda of consider the spell checking a type of code linting, so they can be considered the same category of task. While they are independent, placing them in the same workflow is for more of a grouping the the GUI.

**Review by zivy — APPROVED** [review]

**Comment by zivy** [comment]
@blowekamp, thanks for explaining, sounds reasonable, approved PR.

**Comment by dave3d** [comment]
https://github.com/SimpleITK/SimpleITK/issues/1497

**Pull request merged**
