### PR TITLE
Propagate CMake variables related to compiler standard  and extension

### PR DESCRIPTION
**Pull request by blowekamp**
If the SimpleITK Superbuild was configured with CMake variables such
as:

  -DCMAKE_CXX_STANDARD:STRING=11
  -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON
  -DCMAKE_CXX_EXTENSIONS:BOOL=OFF

Then these options were not propagated to the external projects in the
superbuild.

### CODE REVIEW

**Comment by blowekamp** [comment]
Addresses #260

**Review by hjmjohnson — APPROVED** [review]

**Comment by blowekamp** [comment]
CMAKE_CXX_STANDARD was introduced with CMAKE 3.1. Currently, SimpleITK require CMake>=3.0. Passing this variable if it is defined is not a compatibility issue.

However, the file `sitkCheckRequiredFlags.cmake` may add `std=c++11` to the cxx_flags. Compatibility and interaction needs further investigation, as using two methods to set the CXX standard may pose problems.

**Comment by blowekamp** [comment]
When `std=c++11` is automatically added to CXX_FLAGS or added by the user it will be added to the "compiler_options" for the exported SimpleITK targets. When CXX_STANDARD is requested or required  
, this is currently will not be propagated to the interface for use of the SimpleITK libraries.

https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD

It is not clear how to specify this as part of the interface to a library...

**Comment by blowekamp** [comment]
On linux with cmake 3.7.2, the `SITK_HAS_CXX11` are failing even thought  CMAKE_CXX_STANDARD is set to 11. Manually propagating the CMAKE options to the try_compile make let is success as expected.

**Pull request merged**
