### PR TITLE
Doxygen configuration improvements

### PR DESCRIPTION
**Pull request by blowekamp**
Add interactive SVG. 
Use client side MathJAX for LaTeX math rendering.

### CODE REVIEW

**Comment by blowekamp** [comment]
@jhlegarreta @thewtex @hjmjohnson I'm adding some modern Doxygen client side features here, that ITK may be interested in.

**Review by zivy — APPROVED** [review]

**Comment by jhlegarreta** [comment]
:+1: for changes that make documentation pages have a nicer rendering.

Thanks Brad.

May be once this gets merged, and the new documentation for `master` is deployed, posting here a page of a previous version and a current one would be useful to see the difference.

**Review by dave3d — APPROVED** [review]

**Comment by jhlegarreta** [comment]
Following Brad's announcement in discourse, I have visited the SimpleITK Doxygen website. I chose to visualize:
https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1AdditiveGaussianNoiseImageFilter.html#details

to see how equations or images are rendered. It looks like MathJax is not working out of the box for me. I tried both Chrome and Firefox and the equations are not rendered correctly. Do users need to enable some add-on?

I could not compare to former versions of the documentation: I found no easy way of visiting the documentation of former releases from the Doxygen website itself (also applies to ITK).

**Comment by blowekamp** [comment]
@jhlegarreta The doxygen did not get this update last night due to the URL changes, and scripts ( see #1076 for fixes). You are looking at the output before these changes. The previous Doxygen generation here never had LaTex Math working 🤪 

https://simpleitk.org has a nice pull down menu to go to old versions. Agree it would be nice to have a similar option on the doxygen pages them selves.

**Comment by blowekamp** [comment]
@jhlegarreta The Doxygen was successfully generated and updated last night. The [AdditiveGaussianNoise](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1AdditiveGaussianNoiseImageFilter.html) is a good example the client side MathJAX and the interactive SVG in the inheritance and collaboration diagrams.

**Comment by jhlegarreta** [comment]
> @jhlegarreta The Doxygen was successfully generated and updated last night. The AdditiveGaussianNoise is a good example the client side MathJAX and the interactive SVG in the inheritance and collaboration diagrams.

Yes, I confirm that it looks good on my side as well. Thanks Brad !

**Comment by blowekamp** [comment]
Do you think we should do the same thing for ITK?

**Comment by jhlegarreta** [comment]
> Do you think we should do the same thing for ITK?

I would tend to say yes. Not sure whether there are downsides to it that have prevented from doing it before. A blame on the relevant file in ITK shows that the last edition to the MathJax option, for example, was 9 years ago.

**Comment by hjmjohnson** [comment]
@blowekamp @jhlegarreta FYI:  I plan to apply for a small amount of funding to help support efforts like these.  I'll put this on the list for ITK tasks to do.

**Pull request merged**
