### PR TITLE
Update spell checker to v0.2.2.

### PR DESCRIPTION
**Pull request by dave3d**

### CODE REVIEW

**Comment by blowekamp** [comment]
Doesn't `~=0.2.1`  already pull 0.2.2?

**Comment by dave3d** [comment]
> Doesn't `~=0.2.1` already pull 0.2.2?

I'm not sure?  Would ~=0.2.1 pull all 0.2 variants?

**Comment by blowekamp** [comment]
https://stackoverflow.com/questions/39590187/in-requirements-txt-what-does-tilde-equals-mean

**Comment by dave3d** [comment]
> https://stackoverflow.com/questions/39590187/in-requirements-txt-what-does-tilde-equals-mean

Gotcha.  Yeah, I could have googled it.

**Pull request closed without merging**
