### PR TITLE
Add image IO examples

### PR DESCRIPTION
**Pull request by dave3d**

### CODE REVIEW

**Review by zivy — APPROVED** [review]

**Review by blowekamp — CHANGES_REQUESTED** [review]
You commit history as a merge commit which should be in a PR. Perhaps if you rebase to master it will be removed.

**Comment by dave3d** [comment]
> You commit history as a merge commit which should be in a PR. Perhaps if you rebase to master it will be removed.

Can I just squash them all into one commit?

**Comment by blowekamp** [comment]
Dave

> > You commit history as a merge commit which should be in a PR. Perhaps if you rebase to master it will be removed.
> 
> Can I just squash them all into one commit?

I think you need to remove the merge first or all the commits from the merge will be in there.

**Comment by dave3d** [comment]
> Dave
> 
> > > You commit history as a merge commit which should be in a PR. Perhaps if you rebase to master it will be removed.
> > 
> > 
> > Can I just squash them all into one commit?
> 
> I think you need to remove the merge first or all the commits from the merge will be in there.

Does it look OK now?  I rebased to master and squashed all the commits into one.

**Review by blowekamp — APPROVED** [review]
Looks good. Thanks for cleaning up the history.

**Pull request merged**
