### PR TITLE
Embedded example run of the DicomImagePrintTags code in the Sphinx docs.

### LINKED ISSUE #1798: Embed the output of DicomImagePrintTags in Sphinx
This example only contains text output and is a good starter where the existing Sphinx extensions doctest or other extension should work.
Part of #1797

### PR DESCRIPTION
**Pull request by mbopfNIH**
Uses the sphinx_exec_code directive to run a wrapper script to pass the image file into the main script.

This fixes #1798.

### CODE REVIEW

**Comment by blowekamp** [comment]
I ran it locally. This is what the Sphinx HTML looks like:
image

It looks really good! Maybe some tweaking is needed around the def main line. But I think it is OK to merge to get a first step done.

**Review by zivy — APPROVED** [review]
Very nice improvement of the documentation.

**Comment by blowekamp** [comment]
Let us merge this, since none of the test will build sphinx and it will avoid a conflicts with future work.

**Comment by mbopfNIH** [comment]
That’s odd – I intentionally removed the “def main(args):” line like you requested, and it doesn’t show up in my version. I like yours better, but that’s not what I’m getting. I’ll try updating my master and see which version shows up. Like you said, this approach is a bit finicky for the displayed code.

From: Bradley Lowekamp ***@***.***>
Date: Wednesday, January 11, 2023 at 10:28 AM
To: SimpleITK/SimpleITK ***@***.***>
Cc: Bopf, Mike (NIH/NIAID) [C] ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [SimpleITK/SimpleITK] Embedded example run of the DicomImagePrintTags code in the Sphinx docs. (PR #1814)

I ran it locally. This is what the Sphinx HTML looks like:
[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F321061%2F211845557-b1bd5d71-3d4f-4974-9842-2dbe977fb040.png&data=05%7C01%7Cmbopf%40mail.nih.gov%7C130648b06c53485588b908daf3e88144%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638090477171912933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jhuyTLstL7scZw2WxrQseGCdSS5u0GUH3JLVcOBkNDI%3D&reserved=0>

It looks really good! Maybe some tweaking is needed around the def main line. But I think it is OK to merge to get a first step done.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSimpleITK%2FSimpleITK%2Fpull%2F1814%23issuecomment-1378944181&data=05%7C01%7Cmbopf%40mail.nih.gov%7C130648b06c53485588b908daf3e88144%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638090477171912933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LRiE1vIvlfodvWjAqclaL2%2BaZY5UtbC4hfcSNsrxD%2F0%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJJH23ZAC5SIV7Y3HR5Z3XLWR3GJPANCNFSM6AAAAAATYEK44Y&data=05%7C01%7Cmbopf%40mail.nih.gov%7C130648b06c53485588b908daf3e88144%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638090477171912933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZPXHm7OD9xGxRFao7Az0uGrG1fiIz31tmjLVxhnKA4o%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Pull request merged**
