### PR TITLE
Use ITK's enum typedef to qualify enum value

### PR DESCRIPTION
**Pull request by blowekamp**
The enables compatibility with ITKv5 C++11 call based enums.

### CODE REVIEW

**Review by dave3d — APPROVED** [review]
Coolness

**Review by hjmjohnson — COMMENTED** [review]
ITKv5 instead of ITKv4 in the commit message.

**Comment by blowekamp** [comment]
There are compilation errors on Linux along the lines:
```
/home/blowekamp/src/SimpleITK/Code/Common/src/sitkPimpleTransform.hxx: In member function ‘virtual bool itk::simple::PimpleTransformBase::IsLinear() const’:
/home/blowekamp/src/SimpleITK/Code/Common/src/sitkPimpleTransform.hxx:151:82: error: ‘itk::TransformBase<double>::TransformCategoryType’ is not a class or namespace
       return (this->GetTransformBase()->GetTransformCategory() == TransformBase::TransformCategoryType::Linear);
                                                     
```

This is occurring with gcc 5 only, as other versions seem OK. The error seems to occur with all the changes which add the qualifying typedef for the enum value. @hjmjohnson Have you encountered this? Do you know of a work around or an alternative to access the enum value that will work with both C++03, and C++11?

**Comment by blowekamp** [comment]
This patch has been rebased onto the master which is now using ITKv5.

**Pull request merged**
