### PR TITLE
ENH: Wrapping BinaryPrunningImageFilter

### PR DESCRIPTION
**Pull request by blowekamp**
addresses #800

### CODE REVIEW

**Comment by blowekamp** [comment]
@szhorvat This adds wrapping for the BinaryPruning filter. Can you please try the filter. I was not able to get meaning fully results for the couple images I tried. It would be good to come up with a little test ( preferable with the exiting data ) to test the filter. Thanks!

**Comment by szhorvat** [comment]
@blowekamp I'll try, but it'll take me a little while to compile SimpleITK and get everything working. So I'm posting a simple example image and the expected output after running a pruning filter.

prunable

pruned

**Comment by blowekamp** [comment]
Thanks for the images. The filter seemed to work very well on them. The input just needs to be 1's not 255.

**Comment by blowekamp** [comment]
A test or two with the provided image is needed. Also it need to be determined if this filter works in 3D or if it should only be instantiated in 2D.

**Comment by szhorvat** [comment]
I have not forgotten, it's just been an incredibly busy time for me. Please give me a few more days.

**Comment by blowekamp** [comment]
Updated the testing with the sample image provided. Now we just need to consider if 3D should be supported. Since the filter only works on 0's' and 1's we should consider only supporting uint8_t types to save on compilation time and binary size to keep the SimpleITK package efficient.

**Review by zivy — COMMENTED** [review]
I agree that the filter should only support uint8, to keep the library small. Also, this isn't much of a burden on users as it is trivial to move from other label image types to binary.

Is the UploadBinaryData.sh supposed to be part of this commit or is this an error?

**Comment by blowekamp** [comment]
> Is the UploadBinaryData.sh supposed to be part of this commit or is this an error?

Nope, thanks for spotting it. It was needed from PR #641.

**Review by zivy — APPROVED** [review]
Minor spelling mistake in two places (binnary instead of binary).

**Pull request merged**
