### PR TITLE
Update Superbuild to Lua 5.3.5

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by blowekamp** [comment]
merged in PR #850 

Very close to working!

There appears to be a regression with rendering number in the generated Java code and tests:
The https://open.cdash.org/viewBuildError.php?buildid=6169344

**Review by blezek — COMMENTED** [review]
LGTM

**Review by zivy — APPROVED** [review]
LGTM

**Comment by blowekamp** [comment]
merged as part of #851

**Pull request merged**
