### PR TITLE
sitkLanguageOptions: Improve setting of default value for wrap options

### PR DESCRIPTION
**Pull request by jcfr**
This commit makes sure no calls to "find_package(<languageName>)" are
done if the option WRAP_<languageName> is explicitly set to OFF.

Indeed, systematically calling "find_package()" can have side-effect.
See https://discourse.slicer.org/t/nightly-mac-slicer-4-9-0-2018-03-13-macosx-amd64-does-not-open/2313/7

Change-Id: If58a333b29feef5055f03a4612443020e2a6afa7

### CODE REVIEW

**Comment by jcfr** [comment]
An alternative option would be to ensure option like `CMAKE_DISABLE_FIND_PACKAGE_<packageName>` are propagated down to the inner build.

**Comment by jcfr** [comment]
The commit message in the corresponding Slicer commit should give more context:

```
COMP: update SimpleITK to effectively avoid unwanted find_package calls

This commit reverts the approach implemented in the previous commit. It
failed because SimpleITK has a superbuild structure and the CMAKE_DISABLE_FIND_PACKAGE_*
options are not propagated down to the inner build.

Instead, a patch improving the handling of SimpleITK wrapping options
has been proposed to the upstream project (and in the mean time integrated
in our Slicer fork).

The implemented solution consists in avoiding the call to "find_package()"
if the corresponding WRAP_<languageName> option has explicitly been set or
if WRAP_DEFAULT is set to OFF.
Indeed, there is no need to do these call to find an appropriate default value
for the option since the user (in this case Slicer build system) explicitly
set of value of for the options (eiter directly or by setting WRAP_DEFAULT).

See https://github.com/SimpleITK/SimpleITK/pull/424

List of changes:

$ git shortlog 67872f8..998bdbc --no-merges
Jean-Christophe Fillion-Robin (1):
      sitkLanguageOptions: Improve setting of default value for wrap options


```

**Comment by blowekamp** [comment]
Great! Thanks for the pull request! The

This is some tricky logic and behavior, give me a bit to try it out for a few cases. It looks like this approach will results in multiple calls to the `find_packages` and there could be a macro to reduce some code duplications. I'll work on a refined patch.

**Comment by blowekamp** [comment]
Please see #427  for the proposed improvement. This patch will only call find_package once, and there is some code reduction by keeping the macro.

**Pull request closed without merging**
