### PR TITLE
remove obsolete py2.7 print_function

### PR DESCRIPTION
**Pull request by dave3d**
I've removed all the obsolete import of print_function lines.

### CODE REVIEW

**Comment by blowekamp** [comment]
what is [dict_search.py](https://github.com/SimpleITK/SimpleITK/pull/1594#diff-a917dd8fe27d1de3866bf647139aada6f0a075025884e260e7f16d52ad6df2ff)?

**Comment by dave3d** [comment]
> what is [dict_search.py](https://github.com/SimpleITK/SimpleITK/pull/1594#diff-a917dd8fe27d1de3866bf647139aada6f0a075025884e260e7f16d52ad6df2ff)?

My bad.  Accidentally added it.

**Comment by blowekamp** [comment]
please squash or fix up the commits to remove the noise of the erroneous commit.

**Comment by dave3d** [comment]
> For all the examples, need to check that the code imports in the Documentation.rst for all of them are still valid (the `:lines: 19-` line may need to be modified for some).

Oh yeah.  I'll fix them.

**Comment by dave3d** [comment]
All the Sphinx doc pages look ok.  It seems that the documentation in Examples/Python is not being built.  Is that intentional?

**Review by blowekamp — APPROVED** [review]
LGTM

**Pull request merged**
