### PR TITLE
unpack was moved to table.unpack for Lua 5.2

### PR DESCRIPTION
**Pull request by dave3d**

### CODE REVIEW

**Review by zivy — APPROVED** [review]
Cool overloading.

**Review by blowekamp — CHANGES_REQUESTED** [review]
Currently we require and are using Lua 5.3. It seems to work fine What was the error you encountered? Perhaps a more verbose commit message would better explain the situation.

**Comment by blowekamp** [comment]
Hrmm... Let me see if I have figured this out some more.

We require Lua 5.3 for the code generation. And we provide that in this super build.

This PR is for testing of the Lua *wrapping*. During the configuration of SimpleITK this is usually the system Lua. We don't have such a version requirement for the wrapped version of Lua.

I have been testing with Lua 5.2 on Ubuntu 18.04 LTS, which must be compile with Lua compatibility modes enabled. I am uncertain with versions of Lua we are using in the CI.

**Review by blowekamp — CHANGES_REQUESTED** [review]
This PR now include changes to the Wrapping/Java directory that appear to be mistakenly committed.

**Comment by dave3d** [comment]
> This PR now include changes to the Wrapping/Java directory that appear to be mistakenly committed.

Oops.  I've fixed it with the latest update.

**Review by blowekamp — APPROVED** [review]

**Pull request merged**
