### PR TITLE
Typemap "ret" to attach C finalizer to Image and Transform objects.

### PR DESCRIPTION
**Pull request by richardbeare**
This deals with leaking when these objects are returned
by the procedural interface or Execute method call. Otherwise swig
is only attaching finalizers to the constructor outputs.

Change-Id: I1712bfe9efcbf55bce6f3bcdd8041a487dc14f85

### CODE REVIEW

**Comment by blowekamp** [comment]
This patch will close #131

**Comment by richardbeare** [comment]
I think this should be a bugfix - without these additions and R session will eventually use loads of RAM because simpleitk images returned by filters, as opposed to created directly via constructors, will never be disposed.

**Comment by blowekamp** [comment]
The big concern with this approach is that it specifically handles only these two types. If there are other _new_ object that are returned the the reference counting will be wrong for them too. This really seems like it the underlying problem should be address in SWIG.

However, for SimpleITK I have been unable to find other types that return _new_ object, so this patch does address our immediate needs.

**Comment by blowekamp** [comment]
This patch has been rebased onto the _release_ branch #182

**Comment by richardbeare** [comment]
I think that the typemaps I've used are swig's way of dealing with the problem. I suspect that there must be times when marking objects for deletion by the interpreter is the wrong thing to do, and thus swig forces the user to name the ones to be handled this way.

**Comment by blowekamp** [comment]
I agree that it is SWIG's way. However, the default behavior of SWIG for all the other languages is to assume that SWIG owns the return object, and delete it when the SWIG object goes away. Case in point, when the methods were returning `Self &`,  SWIG would take owner ship and delete the object by default for all the other languages. So we have removed the `return self` when wrapping with SWIG.

I believe that R SWIG  needs to be updated to by default take owner ship of object return

**Pull request closed without merging**
