### PR TITLE
Adding images to the N4 Bias Example

### LINKED ISSUE #1873: Improve the N4 bias field correction example to include images in the output.
https://github.com/SimpleITK/SimpleITK/blob/master/Examples/N4BiasFieldCorrection/Documentation.rst

The inputImage, the log_bias_field, and the corrected_image_full_resolution should be displayed. The bias field may need a color map.

### PR DESCRIPTION
**Pull request by mbopfNIH**
Resolves #1873

### CODE REVIEW

**Comment by mbopfNIH** [comment]
The input image isn't a very good example case for this algorithm, at least not with the defaults. We should find a better input that can benefit from the correction.

I was able to add Ziv's suggestion for the ..list-table and I think it looks pretty good!
Screen Shot 2023-02-08 at 6 53 04 PM

**Comment by mbopfNIH** [comment]
I displayed the default mask, but can remove it if you prefer. I don't think the Log Bias Image needs a color map.

**Review by blowekamp — COMMENTED** [review]
LGTM

**Review by dave3d — APPROVED** [review]
Very nice.

**Pull request merged**
