### PR TITLE
ENH: Use return instead of raising StopIteration (PEP 479)

### PR DESCRIPTION
**Pull request by kaspermarstal**
In Python 3.7, raising StopIteration results in a runtime error as [described here](https://docs.python.org/3/whatsnew/3.7.html):

> PEP 479 is enabled for all code in Python 3.7, meaning that StopIteration exceptions raised directly or indirectly in coroutines and generators are transformed into RuntimeError exceptions. (Contributed by Yury Selivanov in bpo-32670.)

The new behaviour would cause some SimpleITK tests to fail when using Python 3.7 (full PEP is [described here](https://www.python.org/dev/peps/pep-0479/)). This commit uses `return` instead of` raise StopIteration` to end Python iterators as recommended by PEP 479. Tested on Linux, Mac, and Windows using Python 2.7, 3.5, 3.6, and 3.7.

### CODE REVIEW

**Comment by blowekamp** [comment]
Great that you for addressing this issue. There looks like there was previous work done relate here: f80c74f57e5dcb404652e8574151c6e1385e44d7

1. We have Python 3.7 on several systems on [cdash](https://open.cdash.org/index.php?project=SimpleITK), that are not having any test failures. What is needed to produce this problem?
2. Can you please add a test?
3. What versions of Python is this change compatible with?

**Comment by kaspermarstal** [comment]
1. The problem was reproduced here: https://dev.azure.com/kaspermarstal/SimpleElastix/_build/results?buildId=49

    The relevant lines in the CTest logs are:

        2018-12-08T21:00:38.1726710Z 998: ======================================================================
        2018-12-08T21:00:38.1727080Z 998: ERROR: test_2d (__main__.TestImageIndexingInterface)
        2018-12-08T21:00:38.1727330Z 998: testing __getitem__ for 2D image
        2018-12-08T21:00:38.1728480Z 998: ----------------------------------------------------------------------    
        2018-12-08T21:00:38.1728640Z 998: Traceback (most recent call last):
        2018-12-08T21:00:38.1729330Z 998:   File "/Users/vsts/agent/2.142.1/work/1/s/build/SimpleITK-build/Testing/Installation/PythonVirtualenv/lib/python3.7/site-packages/SimpleITK-1.1.0.dev394+g8da5d-py3.7-macosx-10.13-x86_64.egg/SimpleITK/SimpleITK.py", line 4468, in __iter__
        2018-12-08T21:00:38.1729450Z 998:     raise StopIteration
        2018-12-08T21:00:38.1729520Z 998: StopIteration
        2018-12-08T21:00:38.1729570Z 998: 
        2018-12-08T21:00:38.1729630Z 998: The above exception was the direct cause of the following exception:
        2018-12-08T21:00:38.1729690Z 998: 
        2018-12-08T21:00:38.1729740Z 998: Traceback (most recent call last):
        2018-12-08T21:00:38.1729810Z 998:   File "/Users/vsts/agent/2.142.1/work/1/s/Testing/Unit/Python/ImageIndexingTest.py", line 87, in test_2d
        2018-12-08T21:00:38.1730350Z 998:     self.assertImageNDArrayEquals(img[-4:-1:-2,-2:-1:1],nda[-2:-1:1,-4:-1:-2])
        2018-12-08T21:00:38.1730460Z 998:   File "/Users/vsts/agent/2.142.1/work/1/s/Testing/Unit/Python/ImageIndexingTest.py", line 35, in assertImageNDArrayEquals
        2018-12-08T21:00:38.1730550Z 998:     for p,n in zip(img, nda.flat):
        2018-12-08T21:00:38.1730610Z 998: RuntimeError: generator raised StopIteration

    Looks like I didn't have f80c74f in this build and therefore ran the test case with an empty image.

2. Yes, sure. Will add a test.
3. It seems to be compatible with Linux, Mac, and Windows using Python 2.7, 3.5, 3.6, and 3.7 as these tests passed after applying the patch: https://dev.azure.com/kaspermarstal/SimpleElastix/_build/results?buildId=50.

**Comment by blowekamp** [comment]
I think in f80c74f I side stepped this issue, but this may be the correct fix. Great work!

That looks like some nice Azura DevOps. Do you have a configuration to share/contribute?

**Comment by kaspermarstal** [comment]
Thanks!

Yes, the configuration file is here: https://github.com/SuperElastix/SimpleElastix/blob/azure-pipelines/CI/Azure/azure-pipelines.yml. FYI it is still WIP and I am currently investigating how best to run a separate pipeline for building the wheels.

But indeed, it has been pleasent using Azure DevOps so far. Easy to setup, supports Linux, Mac and Windows, the free tier is very generous with compute resources, and a Microsoft representative even reached out on the PR offering help if I had any questions! Super nice.

**Comment by blowekamp** [comment]
Great! Merging into next...

**Pull request merged**
