### PR TITLE
Reduce output verbosity for spell checking

### PR DESCRIPTION
**Pull request by dave3d**
Only print out the spelling errors found.

### CODE REVIEW

**Comment by blowekamp** [comment]
Looks good. I now see these messages:
https://github.com/SimpleITK/SimpleITK/actions/runs/4138289546/jobs/7154509789#step:5:13

**Comment by dave3d** [comment]
Hmmm, it wasn't supposed to print all those file names

**Comment by dave3d** [comment]
Oh wait.  It needs the updated codespell.  It should be better now that I've merged over there.

**Comment by blowekamp** [comment]
I think the GitHub CI is always pulling from code-spell master.

**Comment by blowekamp** [comment]
@Dave Is the patch ready to go?

**Comment by dave3d** [comment]
> @dave Is the patch ready to go?

Yup

**Review by blowekamp — APPROVED** [review]

**Pull request merged**
