### PR TITLE
Adding example illustrating how to read a raw image file.

### PR DESCRIPTION
**Pull request by zivy**

### CODE REVIEW

**Comment by blowekamp** [comment]
Looks like a good example.

To be consistent with the other example and facilitate automatic testing, and validation:
 - please produce an output file and check with a check sum.
 - please guard the use of Show with a check for the SITK_NOSHOW environment variable like what was done here:
https://github.com/SimpleITK/SimpleITK/blob/master/Examples/DicomSeriesReader/DicomSeriesReader.py#L45
  - The other examples don't check for "__main__", please be consistent with them.

**Comment by zivy** [comment]
Addressed points 2 and 3. Changing the example to write an image in the end makes this closer to a test than an example, so I'd like to keep it as is, unless you feel this is really critical.

**Comment by blowekamp** [comment]
Yes, it is the way they are all written and ensures they all keep working.

**Comment by zivy** [comment]
Added checks returning zero if example succeeds or one if failure. This is not validation via file writing, but is consistent with other examples.

**Comment by zivy** [comment]
Add output files and comparison via md5. There is some strange behavior, the md5 for the files written via Python is different from those via R even though the pixel values are the same.

**Comment by blowekamp** [comment]
I'll take a look at this behavior

**Comment by blowekamp** [comment]
I have updated the PR so it works with the test system.

In the future we may add images produced by the example to the Documentation.rst files. For here adding both endings would be nice.

**Comment by blowekamp** [comment]
@ziv @dave3d Please check the review the update I pushed here.

**Pull request merged**
